# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  DATABRICKS_HOST: $(DATABRICKS_HOST)
  DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install databricks-cli
    databricks configure --token <<EOF
    $(DATABRICKS_HOST)
    $(DATABRICKS_TOKEN)
    EOF

    # Deploy all notebooks in the folder
    for notebook in $(find "./U.S. Home Project" -name "*.py"); do
      base=$(basename "$notebook")
      databricks workspace import "$notebook" "/Shared/houseproject/$base" --format SOURCE --overwrite
    done
  displayName: 'Deploy Notebooks to Databricks'